# the random() method - this generates a random real decimal number between 0 and 1.

###### ********* Vectors generated by the vector.random() method have three components, each of which is a random decimal number between -1 and 1****

###### why it is moving at the centre means coz every direction was changing negative
from vpython import *
scene.range = 20
Floor = box(size = vector(100,0.5,40),pos = vector(0,-5,0))
# back = box(size = vector(100,40,0.5),pos = vector(0,0,-20))
# Front = box(size = vector(100,40,0.5),pos = vector(0,0,20))
num_ball = 100 # no. of balls
bucket = [] ## a container in which all balls are kept

for i in range(num_ball):
    ball = sphere()
    ball.color = vector.random()
    ball.radius = random()
    ball.pos = vector(random(),random()+18,random())
    # ball.pos = vector(100+ random()-50,random()+18, 40 + random()-20)
    # ball.velocity = vector(30*random(),10*random(),5*random())  ### the bug was velocity was becoming negative in every direction.
    ball.velocity = 5*vector.random()  ######## giving the exact that motion

    # ball.velocity = vector(0.0,0.0,0.0) ### it shows that it actually changes the direction , there is no random velocity
    ball.acceleration = vector(0.0,-9.8,0.0)

    bucket.append(ball)
# for i in bucket:  ### try to find how can you know exact object rather than address like ( by  printing just i )
#  print(i.color) #### here you can access the object attributes means it need to work in the right way

time = 0.0
dt = 0.01
while(time <20.0):
    rate(1/dt)
    for ball in bucket:
        ball.pos = ball.pos + ball.velocity *dt
        ball.velocity = ball.velocity + ball.acceleration*dt

        # if ball.pos.y < Floor.pos.y:
        #     ball.pos.y = Floor.pos.y
        #### try to understand this below code exact meaning.
        if (ball.pos.y - ball.radius < Floor.pos.y + 0.5 * Floor.size.y):
            ball.pos.y = Floor.pos.y + ball.radius + 0.5 * Floor.size.y
            ball.velocity.y = -(ball.velocity.y)

            ####  right now unable to get the exact motion like woh uss floor ke bahar na jae.
            # if (ball.pos.z -ball.radius) >Front.pos.z+0.5*Front.size.z  :
            #     ball.pos.z =  Front.pos.y + ball.radius + 0.5 * Front.size.y
            #     ball.pos.z = -(ball.velocity.z)
            # elif (ball.pos.z - ball.radius) <back.pos.z+0.5*back.size.z:
            #     ball.pos.z = back.pos.y + ball.radius + 0.5 * back.size.y
            #     ball.pos.z = -(ball.velocity.z)

    time = time+dt



